name: Keep Render Awake

# Run every 10 minutes
on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          curl --fail https://swd6-discord-roller.onrender.com/ || exit 1
