name: Keep Render Awake

# Run every 20 minutes
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          curl --fail https://<your-service>.onrender.com/ || exit 1
